import './globals.css'
import Nav from "./Nav"

export const metadata = {
  title: 'Artimum',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        </body>
    </html>
  )
}
